version: "3.7"
services:
   mcuexpresso-dev:
    build:
      context: ./
      args:
       # Customize your IDE version here
       IDE_VERSION: 11.4.0_6237
       USERNAME: root
       UID: 0
       GID: 0
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=unix:0
    volumes:
      - ./mnt:/mnt
      - ./root:/root
      # dbus
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/machine-id:/var/lib/dbus/machine-id
      - /var/run/dbus:/var/run/dbus
      # X11 Forwarding
      - /tmp/.X11-unix:/tmp/.X11-unix
    image: mcuexpresso-dev:latest
    container_name:  mcuexpresso-dev
